export const parcelStatus = {
    REQUESTED: "REQUESTED",
    APPROVED: "APPROVED",
    DISPATCHED: "DISPATCHED",
    IN_TRANSIT: "IN TRANSIT",
    OUT_FOR_DELIVERY: "OUT FOR DELIVERY",
    DELIVERED: "DELIVERED",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
    BLOCKED: "BLOCKED"
}